export enum Status {
  PLANEJAMENTO = 'A',
  PROJETO_DESENVOLVIMENTO_PRODUTO = 'B',
  PROJETO_DESENVOLVIMENTO_PROCESSO = 'C',
  VALIDACAO_PRODUTO_PROCESSO = 'D',
  ANALISE_ACAO_CORRETIVA = 'E',
  CANCELADO = 'F'
}
